

import logging
from logger.logger import LOGGER_NAME

logger = logging.getLogger(LOGGER_NAME)


class Scrapper(object):
    SCRAPPER_API_UNKNOWN = 0
    SCRAPPER_API_1LUXURYA = 1
    SCRAPPER_API_1ON1LINKS = 2
    SCRAPPER_API_20MICRONS = 3
    SCRAPPER_API_247SINGLEWINDOWSERVICES = 4

    SCRAPPER_API_API = {
        SCRAPPER_API_UNKNOWN: "UNKNOWN",
        SCRAPPER_API_1LUXURYA: "1LUXURYA",
        SCRAPPER_API_1ON1LINKS: "1ON1LINKS",
        SCRAPPER_API_20MICRONS: "20MICRONS",
        SCRAPPER_API_247SINGLEWINDOWSERVICES: "247SINGLEWINDOWSERVICES",
    }
